#!/bin/bash

GREPARGS="--exclude=countwork --exclude=*\.git* -R"
FILES=`find src/ -iname *.cpp -o -iname *.h`


grep $GREPARGS -n -E 'TODO|FIXME|BUGBUG' $FILES

echo "~-Summary-~"
echo "TODOs:   `grep $GREPARGS TODO $FILES | wc -l`"
echo "FIXMEs:  `grep $GREPARGS FIXME $FILES | wc -l`"
echo "BUGBUGs: `grep $GREPARGS BUGBUG $FILES | wc -l`"
echo $FILES
